export const GET_LEAGUE_TABLE_LIST = "GET_LEAGUE_TABLE_LIST";
export const GET_LEAGUE_CLUBS_LIST = "GET_LEAGUE_CLUBS_LIST";
export const SEARCH_BY_CLUB_NAME = "SEARCH_BY_CLUB_NAME";
export const SORT_BY_POINTS = "SORT_BY_POINTS";